# A work flow to get automatic updates about latest dependency versions

name: Dependency Update Check

# Controls when the workflow will run
on:
  # Triggers the workflow every Sat at 12:00 noon
  schedule:
    - cron: '00 12 * * SAT'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  dependency-updates:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Check Dependency Updates
        run: bash ./gradlew dependencyUpdates
        
      - name: Log dependency update report
        run: cat build/dependencyUpdates/dependency_update_report.txt
        
      - name: Send email report
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/github-script@v3
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        with:
          script: |
            const scriptPath = '/./.github/scripts/dependency-report-mail.js'
            const script = require(`${process.env.GITHUB_WORKSPACE}${scriptPath}`)
            script({ })
